# Generated by Django 5.0.13 on 2026-01-29 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('raridade', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('efeito', models.TextField()),
                ('poder', models.IntegerField(blank=True, null=True)),
                ('defesa', models.IntegerField(blank=True, null=True)),
                ('custo_mana', models.IntegerField()),
                ('treshold_agua', models.IntegerField(default=0)),
                ('treshold_vento', models.IntegerField(default=0)),
                ('treshold_fogo', models.IntegerField(default=0)),
                ('treshold_terra', models.IntegerField(default=0)),
                ('printing', models.CharField(choices=[('Alpha', 'Alpha'), ('Alpha (foil)', 'Alpha (foil)'), ('Beta', 'Beta'), ('Beta (foil)', 'Beta (foil)'), ('Arthurian_Legends', 'Arthurian Legends'), ('Arthurian_Legends (foil)', 'Arthurian Legends (foil)'), ('Dragonlords', 'Dragonlords'), ('Dragonlords (foil)', 'Dragonlords (foil)'), ('Gothic', 'Gothic'), ('Gothic (foil)', 'Gothic (foil)')], max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cartas/')),
            ],
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_venda', models.BooleanField(default=False)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadosorcery.carta')),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadosorcery.colecao')),
            ],
            options={
                'unique_together': {('carta', 'colecao')},
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cartas', models.ManyToManyField(to='mercadosorcery.posse')),
            ],
        ),
        migrations.AddField(
            model_name='colecao',
            name='cartas',
            field=models.ManyToManyField(through='mercadosorcery.Posse', to='mercadosorcery.carta'),
        ),
    ]
