# Generated by Django 5.0.13 on 2026-02-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadosorcery', '0002_alter_carta_custo_mana_alter_carta_printing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posse',
            name='a_venda',
        ),
        migrations.AddField(
            model_name='posse',
            name='estado_carta',
            field=models.CharField(choices=[('NM', 'NearMint'), ('SP', 'Slightly Played'), ('MP', 'Moderatedly Played'), ('HP', 'Highly Played'), ('D', 'Damaged')], default='NM', max_length=50),
        ),
        migrations.AddField(
            model_name='posse',
            name='status',
            field=models.CharField(choices=[('VENDENDO_PELO_PRECO_MEDIO', 'Vendendo_Pelo_Preco_Medio'), ('VENDENDO_PELO_MENOR_PRECO', 'Vendendo_Pelo_Menor_Preco'), ('VENDENDO_PELO_PRECO_DEFINIDO', 'Vendendo_Pelo_Preco_Definido'), ('FORA_DE_VENDA', 'Fora_De_Venda')], default='FORA_DE_VENDA', max_length=50),
        ),
    ]
