steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/firebaseapphosting-images/mercadosorcery:latest',
      './mysite'
    ]

# 2. Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/firebaseapphosting-images/mercadosorcery:latest']
