# Generated by Django 5.2.11 on 2026-02-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('printing', models.CharField(max_length=10)),
                ('imagem', models.CharField(blank=True, max_length=512, null=True)),
                ('mana_cost', models.CharField(blank=True, max_length=50)),
                ('cmc', models.FloatField(default=0.0)),
                ('type_line', models.CharField(blank=True, max_length=255)),
                ('oracle_text', models.TextField(blank=True)),
                ('power', models.CharField(blank=True, max_length=10)),
                ('toughness', models.CharField(blank=True, max_length=10)),
                ('rarity', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Posse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_carta', models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DM', 'Damaged')], max_length=2)),
                ('status', models.CharField(choices=[('NOT_FOR_SALE', 'Fora de Venda'), ('FOR_SALE', 'À Venda'), ('TRADING', 'Trocando')], max_length=20)),
                ('preco_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
