# Generated by Django 5.0.13 on 2026-01-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadosorcery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='custo_mana',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carta',
            name='printing',
            field=models.CharField(choices=[('Alpha', 'Alpha'), ('Alpha (foil)', 'Alpha (foil)'), ('Beta', 'Beta'), ('Beta (foil)', 'Beta (foil)'), ('Arthurian_Legends', 'Arthurian Legends'), ('Arthurian_Legends (foil)', 'Arthurian Legends (foil)'), ('Dragonlords', 'Dragonlords'), ('Dragonlords (foil)', 'Dragonlords (foil)'), ('Gothic', 'Gothic'), ('Gothic (foil)', 'Gothic (foil)'), ('Promotional', 'Promotional'), ('Promotional (foil)', 'Promotional (foil)')], max_length=100),
        ),
    ]
