# Generated by Django 5.2.11 on 2026-02-06 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mercadosorcery', '0001_initial'),
        ('socialentities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_perfil/')),
                ('role', models.CharField(blank=True, choices=[('PACIENTE', 'Paciente'), ('MEDICO', 'Medico')], max_length=50, null=True, verbose_name='função')),
            ],
        ),
        migrations.AddField(
            model_name='colecao',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lista',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posse',
            name='carta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadosorcery.carta'),
        ),
        migrations.AddField(
            model_name='posse',
            name='colecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadosorcery.colecao'),
        ),
        migrations.AddField(
            model_name='lista',
            name='cartas',
            field=models.ManyToManyField(to='mercadosorcery.posse'),
        ),
    ]
