# Generated by Django 5.0.13 on 2026-02-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadosorcery', '0003_remove_posse_a_venda_posse_estado_carta_posse_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posse',
            old_name='preco',
            new_name='preco_usd',
        ),
        migrations.AlterUniqueTogether(
            name='posse',
            unique_together=set(),
        ),
    ]
