# Generated by Django 5.0.6 on 2026-02-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadosorcery', '0004_rename_preco_posse_preco_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='card_images/'),
        ),
    ]
