# Generated by Django 5.0.6 on 2026-02-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadosorcery', '0004_rename_preco_posse_preco_usd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='imagem',
        ),
        migrations.AddField(
            model_name='carta',
            name='link_imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
