# Generated by Django 5.0.6 on 2026-02-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadosorcery', '0005_alter_carta_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_comprimidas/'),
        ),
    ]
