# Generated by Django 5.0.6 on 2026-02-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadosorcery', '0006_alter_carta_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='imagem',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
