# Generated by Django 5.0.6 on 2026-02-04 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadosorcery', '0007_alter_carta_imagem'),
        ('socialentities', '0007_remove_socialentity_cpf_remove_socialentity_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_perfil/')),
                ('role', models.CharField(blank=True, choices=[('PACIENTE', 'Paciente'), ('MEDICO', 'Medico')], max_length=50, null=True, verbose_name='função')),
            ],
        ),
        migrations.RemoveField(
            model_name='carta',
            name='custo_mana',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='defesa',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='efeito',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='poder',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='raridade',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='treshold_agua',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='treshold_fogo',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='treshold_terra',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='treshold_vento',
        ),
        migrations.RemoveField(
            model_name='colecao',
            name='cartas',
        ),
        migrations.AddField(
            model_name='carta',
            name='cmc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carta',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carta',
            name='oracle_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='carta',
            name='power',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='carta',
            name='rarity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carta',
            name='scryfall_id',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='carta',
            name='toughness',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='carta',
            name='type_line',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='carta',
            name='printing',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lista',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='posse',
            name='estado_carta',
            field=models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DM', 'Damaged')], max_length=2),
        ),
        migrations.AlterField(
            model_name='posse',
            name='status',
            field=models.CharField(choices=[('NOT_FOR_SALE', 'Fora de Venda'), ('FOR_SALE', 'À Venda'), ('TRADING', 'Trocando')], max_length=20),
        ),
    ]
