# Generated by Django 5.0.6 on 2026-02-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialentities', '0002_alter_socialentity_cpf_alter_socialentity_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialentity',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='role',
            field=models.CharField(choices=[('PACIENTE', 'Paciente'), ('MEDICO', 'Medico')], max_length=50, null=True, verbose_name='função'),
        ),
    ]
