# Generated by Django 5.0.6 on 2026-02-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialentities', '0003_alter_socialentity_cpf_alter_socialentity_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialentity',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='sobrenome'),
        ),
    ]
