# Generated by Django 5.0.6 on 2026-02-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialentities', '0004_alter_socialentity_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialentity',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='role',
            field=models.CharField(blank=True, choices=[('PACIENTE', 'Paciente'), ('MEDICO', 'Medico')], max_length=50, null=True, verbose_name='função'),
        ),
    ]
