# Generated by Django 5.0.6 on 2026-02-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialentities', '0005_alter_socialentity_cpf_alter_socialentity_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialentity',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
