# Generated by Django 5.0.6 on 2026-02-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialentities', '0006_alter_socialentity_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialentity',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='socialentity',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='socialentity',
            name='role',
        ),
    ]
