# Generated by Django 5.0.6 on 2026-02-04 20:59

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialentities', '0007_remove_socialentity_cpf_remove_socialentity_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialentity',
            name='username',
            field=models.CharField(default=1, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
